### ISSUE TITLE
CAPTCHA solution is included in the JWT in plain text

### ISSUE THREAD

**Issue by konradh** [zfish85/flask-includes-captcha#7]
The solution to the CAPTCHA challenge is included in the the JWT in unencrypted form. Therefore, the challenges can be solved automatically without any effort. Ideally the solution should be encrypted with a probabilistic encryption algorithm.

**Comment by zfish85** [comment]
Hi @konradh, many thanks for reporting this issue. In version 0.1.1 I replaced JSON Web Signature (JWS) with JSON Web Encryption (JWE) . Thus, the solution of the CAPTCHA chalange is now now transmitted in an encrypted JWT.
